title: Panagiotis Christakakis # your name (or website title) here
logo: "/images/CV_Circular.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MSc studies in Artificial Intelligence and Data Analytics|BSc Applied Informatics, UoM
  <br><br>
  Thessaloniki, Central Macedonia, Greece 
  <br><br>
  <a href="mailto:panoschristakakis@gmail.com"><i class="fa fa-envelope"></i> Email</a>
  <a href="https://www.linkedin.com/in/christakakis/"><i class="fa fa-linkedin"></i> LinkedIn Profile</a>
  <a href="https://github.com/christakakis"><i class="fab fa-github"></i> GitHub Profile</a>
  
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-E9XKMB88S4 # your Google Analytics tracking ID here
