title: <p align="center"> Panagiotis Christakakis </p>

logo: "/images/CV_Circular.png?raw=true"
  
description:
  <p align="center">
  <a href="pdf/Christakakis_CV.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/christakakis/">LinkedIn</a> |
  <a href="https://github.com/christakakis">GitHub</a>
  <a href="https://scholar.google.com/citations?user=F3gOMO4AAAAJ&hl">Google Scholar</a>
  </p>
  
  <p align="justify">
  Working as Research Assistant at CERTH - The Centre for Research & Technology
  <br><br>
  Currently pursuing a Master's degree in Artificial Intelligence and Data Analytics at University of Macedonia.
  <br><br>
  Thessaloniki, Central Macedonia, Greece
  <br><br>
  </p>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-E9XKMB88S4 # your Google Analytics tracking ID here
